spring.application.name=literature-review-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/literature_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=YOUR_GEMINI_API_KEY_HERE